### ISSUE TITLE
store_location needed?

### ISSUE THREAD

**Issue by nik736** [nabeelamjad/poke-api#12]
Hi,

is store_location needed? It's in all your examples but I am just wondering if it is required/expected or if I can simply skip it?

Thanks!!

**Comment by nabeelamjad** [comment]
I think it depends on your calls, if you want to get map objects then it may be required. It is mostly used for the 'heartbeat' (that is if you want to automatically move around in the game using the API). Your location is passed with every `call` you make to the game (indicating your position). It might be good to store it to avoid getting banned (in any case use a throwaway).

If all you want to do is get player information and such then I don't think it is required.

**Comment by nik736** [comment]
ok, thank you for the fast answer.
