### ISSUE TITLE
Can't use as gem dependency

### ISSUE THREAD

**Issue by xssc** [nabeelamjad/poke-api#17]
Do you plan to push this to rubygems.org? You can't use a git source as a gem dependency

**Comment by nabeelamjad** [comment]
You can if you use Bundler but you're right, I should.

The reason is that someone already has a gem called `poke-api` and I had no idea until after the project.

**Comment by xssc** [comment]
You can change the name in the .gemspec file and still have it as `require 'poke-api'` after its installed.

**Comment by nabeelamjad** [comment]
I'll try and think to come up with a name, maybe `poke-go-api`

**Comment by nabeelamjad** [comment]
Commit a6adf86a1231ea69db78255cbf526bea8da207e9 has set the gem up as `poke-go-api`, I've updated the readme as well now.

**Comment by xssc** [comment]
Nice, thanks!
