### ISSUE TITLE
re-login fails repeatedly

### ISSUE THREAD

**Issue by xssc** [nabeelamjad/poke-api#22]
I am creating an instance of Poke::API::Client and logging in, if it fails, and I try to re-log in, it fails continuously unless I create a new instance, I would try to help further but I had no luck getting it to fail when I turn logs to debug (tried for like 15 mins)

**Comment by xssc** [comment]
My guess would be an instance variable and seeing that its throwing a proto fault it has to be coming from inside `fetch_endpoint`. I think it may be related to `@endpoint`. I will try to test later

**Comment by nabeelamjad** [comment]
Interesting, I'll have to play with this later (hard to reproduce because my logins aren't failing)

**Comment by xssc** [comment]
I have not had time to test this but, This commit, https://github.com/nabeelamjad/poke-api/commit/8f3caa91adb07c1e636dd9e9b71cfec4ae0bde5b, removed a line that checks if the `apiurl` is empty and there is also no check to see if its empty in `fetch_endpoint`(client.rb) so `@endpoint` presumably gets set to `https:///rpc`, because its an empty string (if auth fails)

**Comment by nabeelamjad** [comment]
Yeah, I'll fix the issue with fetch_endpoint so it doesn't overwrite `@endpoint` to an empty string or something.

**Comment by nabeelamjad** [comment]
Fixed in 5099412ccb068a7262bb113011558bbb40c7a06d and pushed as a new release.

**Comment by xssc** [comment]
Thanks, that should fix it!
