### ISSUE TITLE
Use auth ticket if one exist and updated error messages.

### ISSUE THREAD

**Issue by xssc** [nabeelamjad/poke-api#24]
Cna you implement using the auth ticket instead of using the oauth token, Seems to get errors a lot using token. Also can you add new error/log messages for IP ban/ throttle. 

As seen here: https://github.com/tejado/pgoapi/blob/master/pgoapi/rpc_api.py#L122

**Comment by nabeelamjad** [comment]
I'll look into implementing this in a day or two, I need to refresh the protos and clean the structure as well (so we don't end up with a lot of folders and files).

**Comment by xssc** [comment]
alright sounds good

**Comment by nabeelamjad** [comment]
I had a shot at this however it seems something is wrong as the `auth_ticket` I get back in `@response` is still in bytes (as opposed to base64), not sure what the issue is. I'll throw up a WIP branch later today, I've tried a bunch of things already related to encoding types.

**edit**
Added commit https://github.com/nabeelamjad/poke-api/commit/ad9e0fef288174d4f804d87ba829b52ec4fffef3 to wip branch (still incomplete and not working)

**Comment by xssc** [comment]
An update on this: While currently the whole API is broken it seems after the initial request the server doesnt take tokens anymore, only tickets

**Comment by nabeelamjad** [comment]
Are you sure? It's working for me (using PTC, not tried Google) to keep generating requests such as `get_player` or `get_inventory` and they're returning just fine. It seems the only part broken right now is `get_map_objects`, I guess it'll be a waiting game till someone reverse-engineers to see what they changed.

I'll try and see if I can get the Auth ticket figured out, basically everything is working fine with the exception that the Auth ticket returned is in the wrong format (needs to be base64, not bytes). It might be related to the google-protobuf gem for Ruby, I will have a look at Python when I get the time to see if something is different in the way those messages are encoded and decoded.

**Comment by nabeelamjad** [comment]
Done, latest release has implemented this. I'll probably need to make some tweaks later down the line but it should work for now.
