### ISSUE TITLE
Does not re-set api_url

### ISSUE THREAD

**Issue by xssc** [nabeelamjad/poke-api#27]
Sometimes when a status is unsuccessful, it will return a code of 53 and a new api url. Can you add a method that checks for this and updates `@endpoint` accordingly. example response:

```
{:GET_PLAYER=>{:success=>false, :player_data=>nil}, :status_code=>53, :api_url=>"pgorelease.nianticlabs.com/plfe/327", :error=>""}
```

**Comment by nabeelamjad** [comment]
Do we want the `@endpoint` to update in this case I assume?

**Comment by xssc** [comment]
Yes, if they give an api url, it should be set.

**Comment by nabeelamjad** [comment]
So as long as it returns an `API_URL` that isn't blank it should be set, correct? (regardless of status code)

**Comment by xssc** [comment]
Correct.

**Comment by nabeelamjad** [comment]
46e0d6d5761cff17f4b1157fedcf1021d50fc515 should fix this (I've change the structure slightly so the endpoint is handled at the response level), I've also added some more debugging for protocol buffer responses.
