### ISSUE TITLE
Adding proxy support to HTTPClient

### ISSUE THREAD

**Issue by mxgr** [nabeelamjad/poke-api#31]
Since Niantic is now blocking calls from major cloud services through IP detection - is there anyway we would implement the use of a proxy for HTTPClient ?

It could work this way:

`client.store_proxy(url, user, pass)`

And

```
def initialize(auth, pos, endpoint, proxy=nil, proxy_user=nil, proxy_password=nil)
  @access_token = auth.access_token
  @provider     = auth.provider
  @endpoint     = endpoint
  @position     = pos
  @client       = HTTPClient.new(proxy)
  @client.set_proxy_auth(user, password)
  @client.header["User-Agent"] = 'PokeAPI/0.0.1'
  @start_time   = (Time.now.to_f * 1000).to_i
end
```

https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/request_builder.rb

**Comment by nabeelamjad** [comment]
Yep sounds good, I'll add a proxy functionality using HTTPClient in the next build (after today's build).

**Comment by nabeelamjad** [comment]
Actually it might not even be required, it seems `HTTPClient` can detect an environment variable to set up a proxy instead.

Example:

``` ruby
2.3.1 :001 > ENV['HTTP_PROXY'] = 'http://username@password:localhost:8080'
 => "http://username@password:localhost:8080"
2.3.1 :002 > HTTPClient.new.proxy
 => #<Addressable::URI:0xd2a1b8 URI:http://username@password:localhost:8080>
```

It might be easier just to mention this in the readme rather than trying to add another method.

**Comment by nabeelamjad** [comment]
I've added a mention in the README and I'll leave this as it is. If there's something else that I've missed please let me know.

**Comment by mxgr** [comment]
@nabeelamjad yes that's good way to sort this problem out I didn't see this, but let's say there are 200 accounts logged in the service and we want to use one IP per account - one single proxy won't be sufficient to do so

**Comment by mxgr** [comment]
@nabeelamjad So I just tried the http_proxy env var method, setting this up with a major proxy provider authentication, I get this error:
`Poke::API::Errors::LoginFailure: Unable to login to GOOGLE => [407 "Proxy Authentication Required" @ /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb:119:in`error!']`

Seems to be because:

> This happens because Ruby's Open-URI library, which we use to talk to the GitHub API, does not support credentials in the proxy URI. The Ruby maintainers have not been receptive to changing this, as passing credentials in this manner is deprecated by more recent URI RFCs.

https://github.com/Homebrew/legacy-homebrew/issues/32041

I think the only way to get HTTPClient to use a various number of proxies would be through:
`@client       = HTTPClient.new(proxy)
  @client.set_proxy_auth(user, password)`

**Comment by nabeelamjad** [comment]
Oh okay, I see. I'll add it in then for the next build.

**Comment by nabeelamjad** [comment]
This has been implemented now, see [README](https://github.com/nabeelamjad/poke-api/blob/master/README.md) under **Proxy Support** section.

Let me know if you have any issues.
