### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by selivandex** [nabeelamjad/poke-api#32]
Hey 

What is encryption file and how i can get it?

**Comment by nabeelamjad** [comment]
The encryption file itself is copyrighted and thus not provided nor held by us. It does appear [here](https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom) on a different repository, however we are not responsible for any of these (and we do not know if these files are legitimate or not, use at your own risk).

**Comment by selivandex** [comment]
How did you tested `get_map_objects` then?

**Comment by nabeelamjad** [comment]
We had _someone_ test it for us :).

**Comment by selivandex** [comment]
I use Mac OS El Capitan and trying to use this file: https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/libencrypt-osx-64.so

And getting this error: 

```
Poke::API::Errors::UnknownProtoFault - An unknown proto fault has occured => [unknown type: size_t input_size @ /Users/selivanov/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle/cparser.rb:171:in `parse_ctype']:
```

Can you help me with this?

**Comment by nabeelamjad** [comment]
Update your Ruby to 2.3.0+, it's a known issue with older versions of Ruby on Mac.
