### ISSUE TITLE
get_map_objects always returns with empty pokemon arrays

### ISSUE THREAD

**Issue by krzkrzkrz** [nabeelamjad/poke-api#35]
Not sure if I am getting this.

I do something like:

```
require 'poke-api'
require 'awesome_print'

# Instantiate our client
client = Poke::API::Client.new

# Both PTC/Google available as authentication provider
client.store_location('New York')
client.store_lat_lng(40.712906, -74.007333) # Some random coordinates from NY (pulled from Google Maps)

client.login('some_username', 'password_here', 'ptc')

cell_ids = Poke::API::Helpers.get_cells(client.lat, client.lng)

# Construct map objects call
client.get_map_objects(
  latitude: client.lat,
  longitude: client.lng,
  since_timestamp_ms: [0] * cell_ids.length,
  cell_id: cell_ids
)

resp = client.call

puts resp.response
```

All I get are responses with no results:

```
            [ 0] {
                            :s2_cell_id => some_cell_id_here,
                  :current_timestamp_ms => 1470811515476,
                                 :forts => [],
                          :spawn_points => [],
                         :wild_pokemons => [],
                       :deleted_objects => [],
                     :is_truncated_list => false,
                        :fort_summaries => [],
                :decimated_spawn_points => [],
                    :catchable_pokemons => [],
                       :nearby_pokemons => []
            },
```

As in `wild_pokemons`, `catchable_pokemons` and `nearby_pokemons` always returns with an empty array `[]`. Is there something I am missing?

**Comment by nabeelamjad** [comment]
You are missing the activation for the signature, without that map object call always returns empty. 

Have a look at this [example file](https://github.com/nabeelamjad/poke-api/blob/master/examples/spiral_search.rb#L111) (issue #32 might give you more information on this).

**Comment by krzkrzkrz** [comment]
So the encryption file is used to create a signature. Cant the signature be generated with something like. Pseudo code:

```
GOOGLE_MAPS_API_CLIENT_ID = 'gme-xyz'
GOOGLE_MAPS_API_CRYPTO_KEY = 'private_key'
GOOGLEAPIS_HTTP_URL = 'http://maps.googleapis.com'
REVERSE_GEOCODING_ENDPOINT_JSON = '/maps/api/geocode/json'

str_latlng = lat.to_s + ',' + lon.to_s
encoded_params = URI.encode_www_form({'latlng' => str_latlng, 'client' => GOOGLE_MAPS_API_CLIENT_ID})
decoded_key = Base64.urlsafe_decode64(GOOGLE_MAPS_API_CRYPTO_KEY)
url_to_sign = REVERSE_GEOCODING_ENDPOINT_JSON + '?' + encoded_params
digest = OpenSSL::Digest.new('sha1')
signature = OpenSSL::HMAC.digest(digest, decoded_key, url_to_sign)
encoded_signature = Base64.urlsafe_encode64(signature)
signed_url = GOOGLEAPIS_HTTP_URL + REVERSE_GEOCODING_ENDPOINT_JSON + '?' + encoded_params + '&signature='+encoded_signature
```

Does `activate_signature()` expect a specific type of value?

**Comment by krzkrzkrz** [comment]
Apparently, `activate_signature()` expects a file path:

```
      def activate_signature(file_path)
        if File.exist?(file_path)
          logger.info "[+] File #{file_path} has been set for signature generation"
          @sig_path = file_path
        else
          raise Errors::InvalidSignatureFilePath, file_path
        end
      end
```

Wondering if we could just generate our own signature and pass this along instead?

**Comment by nabeelamjad** [comment]
You can't provide any signature of your own, the signature is composed of various hashes of your requests, authentication,  timestamps and so on serialized into bytes using Google's protobuf. Have a look at [**`signature.rb`**](https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/signature.rb).

The signature furthermore needs to be encrypted with Niantic's encryption method (which the file provides). Anything else will result in empty map objects, the only way is to get the encryption file for your platform and activate it using the given method before any map object calls (issue #32). 

All you need is the encryption file, call `activate_signature(path/to/file)`  and it will do the rest for you (including generating and encrypting the signature)

**Comment by krzkrzkrz** [comment]
Thanks for that clarification
