### ISSUE TITLE
Trying to understand fetch_ticket

### ISSUE THREAD

**Issue by krzkrzkrz** [nabeelamjad/poke-api#36]
I am trying to understand this (https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/auth/ptc.rb):

```
        def fetch_ticket(data)
          logger.debug '[>] Fetching PTC ticket'

          ticket = begin
            @client.post_content(PTC_LOGIN_URL, data)
          rescue StandardError => ex
            ex.res.http_header.request_uri.to_s.match(/ticket=(.*)/)[1]
          end

          fetch_access_token(ticket)
        end
```

I'm tried running the code individually. It seems `httpclient` lib fails unexpectedly, thats why you need the `begin` block there. The `ticket` is used to generate the access token on the next method.

Doing the same thing on `httparty` (another http gem), doesnt render any errors:

Take for example:

```
JSON.parse(
  HTTParty.post(
    ptc_login_url,
    headers: {
      'agent_name' => 'PokeAPI/0.0.1'
    },
    body: {
      data: {
        username: 'some_username',
        password: 'password',
        _eventId: 'submit',
        lt: json_response['lt'],
        execution: json_response['execution']
      }
    }
  )
)
```

However, the response I get instead is `{"lt"=>"LT-23868518-ohkebxUhorQIFc11V3441qrSMOhFdF", "execution"=>"e1s1"}`

Instead of what you currently need for the ticket: `ST-7486015-NGPOWEQLoxc2mJM4flun-sso.pokemon.com`

Am I missing something with the HTTParty approach?

**Comment by nabeelamjad** [comment]
Yep, you're not storing cookies (HTTPClient does this for you), instead HTTParty generates a new clean slate every request.

**Comment by krzkrzkrz** [comment]
At this point, I am guessing, its just a matter of passing the cookie from the previous requests, into the new HTTParty requests?

**Comment by nabeelamjad** [comment]
Sounds about right, the best way as always is to open the page yourself with a web browser and try to replicate what's going on. Google Chrome's developer tools are very helpful in seeing what exactly is being done 

Take for example going to https://sso.pokemon.com/sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize (as it's a get request), the developer tools you can see Application -> Cookies that are being set (these are the ones you probably want to include in your next post).

**Comment by nabeelamjad** [comment]
I also need to mention that Niantic in no way or shape conforms to the OAuth 2.0 Authentication framework laid out in [RFC 6749](https://tools.ietf.org/html/rfc6749), instead they have some very _bizarre_ stuff going on.

**Comment by krzkrzkrz** [comment]
That is strange. Im still not getting a valid ticket response. I keep getting a new `LT` response.

I've tried a variation of setting the cookie via HTTParty. Still no go. Latest code is:

```
  # get_response.headers['set-cookie'] returns something like "JSESSIONID=88CAE36BF504FB1159A96106561FC381-n2; Path=/sso"

  HTTParty.post(
    ptc_login_url,
    headers: {
      'agent_name' => 'PokeAPI/0.0.1',
      # 'cookies' => get_response.headers['set-cookie'],
      # 'Cookie' => get_response.headers['set-cookie'],
      # 'cookie' => get_response.headers['set-cookie'],
      'Set-Cookie' => get_response.headers['set-cookie'],
      # cookie: { :'JSESSIONID' => get_response.headers['set-cookie'].split(';')[0] },
    },
    # cookies: { "JSESSIONID" => get_response.headers['set-cookie'] },
    body: {
      data: {
        username: username,
        password: pwd,
        _eventId: 'submit',
        lt: JSON.parse(get_response.parsed_response)['lt'],
        execution: JSON.parse(get_response.parsed_response)['execution']
      }
    }
  )
```

**Comment by nabeelamjad** [comment]
A cookie appears to have more values, no idea how relevant they are as I've never tried using it via HTTParty.

``` ruby
#[#<WebAgent::Cookie:
  name="JSESSIONID", 
  value="FEDC2FD8E498AB429BD6F71B3AE8CFAA-n14", 
  domain="sso.pokemon.com", 
  for_domain=false, 
  path="/sso", 
  secure=false, 
  httponly=false, 
  expires=nil, 
  max_age=nil, 
  created_at=2016-08-10 11:32:04 +0000, 
  accessed_at=2016-08-10 11:32:04 +0000 
  origin=https://sso.pokemon.com/sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize
#>]
``
```

**Comment by nabeelamjad** [comment]
Going to close this issue down as it's not really an issue (if you want information on how things are done then you can always look at the source code for HTTPClient, though I have to warn you that their code is not pretty to read).
