### ISSUE TITLE
Update signature and allow custom data

### ISSUE THREAD

**Issue by xssc** [nabeelamjad/poke-api#39]
Can you please update the signature proto to reflect the updates in this commit: https://github.com/AeonLucid/POGOProtos/commit/b65d4b56f02a1182bd81572bcee3a32944c47885

And is it possible to make it so you can set device/gps/sensor/activity info for each request. as currently it sets the signature without any of those fields.

**Comment by nabeelamjad** [comment]
Yep sure, any ideas for what kind of values to use? I don't play the game myself so wouldn't have a clue. If I can get some sample data I could fill it in (and randomize it to some degree)

**Comment by xssc** [comment]
Well I was really hoping it could be configurable by projects using this API, so they can determine, how/what they want to fill in.

**Comment by nabeelamjad** [comment]
I'll have a look into it to allow projects to configure it then for each request made, if not filled it would send it blank without those filled.

**Comment by nabeelamjad** [comment]
It seems the latest protobufs don't work for the signature. 

https://github.com/AeonLucid/POGOProtos/commit/b65d4b56f02a1182bd81572bcee3a32944c47885 changes `request_hash` from uint64 to int64 (which breaks it), changing that line back to uint64 works fine. I'm not sure behind the reasoning for this, I highly doubt our hash function can return a negative value? (I've never seen it generate negative values, might be possible?)

**Comment by nabeelamjad** [comment]
I've been quite busy this week but I'll get this implemented in the next two days (at least the manual options for Signature), the protobufs I might hold off until they are fixed.

**Comment by nabeelamjad** [comment]
Both latest protobufs and optional signature info are added in the latest release now (0.2.0), the readme will indicate on how to use these per request.
