### ISSUE TITLE
Unkown proto fault when using @client.call or @client.login method

### ISSUE THREAD

**Issue by emilenriquez** [nabeelamjad/poke-api#41]
An unknown proto fault has occured => [Error occurred during parsing: Unmatched ENDGROUP tag. @ /home/deploy/.bundler/pokedex_development/ruby/2.2.0/bundler/gems/poke-api-5f1a75a6e4ed/lib/poke-api/response.rb:16:in `decode']

**Comment by emilenriquez** [comment]
<img width="1279" alt="screen shot 2016-08-18 at 14 52 43" src="https://cloud.githubusercontent.com/assets/3405569/17764636/2672b99e-6553-11e6-9aa9-8cb0341133f6.png">

**Comment by nabeelamjad** [comment]
Can you log in at all or does it fail entirely? I would suggest to try different credentials and/or update Ruby. The error does suggest that you received no response from Niantic.

If you could run with debug mode on and paste the response (filter out whatever is personal) then I might be able to see what's going on.

**Comment by emilenriquez** [comment]
updated ruby to 2.3.1 already and on my localhost this wasn't a problem but after deploying to the server it fails .

**Comment by emilenriquez** [comment]
btw thanks for following this one up.

> Can you log in at all or does it fail entirely?

it can get the google credentials 
but after setting up or calling @client.login method then the above error occurs @nabeelamjad

**Comment by nabeelamjad** [comment]
Oh. I see.

Juts so you know major cloud providers all over the world are banned to received responses from Niantic, so most likely yours is too (wherever you host it). This is in a bid to crack down any API calls unfortunately, there's not much you can do about it (you can run it locally or have a proxy for your webserver that routes it elsewhere first).

If you enable DEBUG logging you'll notice your response is empty most likely with an error status code.

I do agree though, this is a valid issue for me to update in terms of useful status code error messages so people know what's going on.

**Comment by emilenriquez** [comment]
I see. thanks @nabeelamjad. I wonder how these services get their data though
- pokeiv.net
- pgnexus.gg

**Comment by emilenriquez** [comment]
additional debug 

```
Started POST "/pokemongo/google_login?method=post" for 173.245.48.103 at 2016-08-18 18:34:39 +0900
Processing by PokemongoController#google_login as HTML
  Parameters: {"utf8"=>"?~\~S", "authenticity_token"=>"Jf8eddrdKUUL+vS6Q25HECsHhTfzKIxz6uyRTX4kQwFAIUHq1FWWp8zHWBJj/OlCBm99qjpw8pyzaN+MNSomYA==", "token"=>"4/YHOCQFLMhj-f6kN9dezoIweKRchF_bo14YRoFmyGtyc", "commit"=>"Login", "method"=>"post"}
Completed 500 Internal Server Error in 676ms (ActiveRecord: 0.0ms)

Poke::API::Errors::UnknownProtoFault (An unknown proto fault has occured => [Error occurred during parsing: Unmatched ENDGROUP tag. @ /home/deploy/.bundler/pokedex_development/ruby/2.3.0/bundler/gems/poke-api-5f1a75a6e4ed/lib/poke-api/response.rb:16:in `decode']):
  app/helpers/pokemongo_helper.rb:36:in `init_pokemongo_data'
  app/controllers/pokemongo_controller.rb:13:in `google_login'
```

**Comment by nabeelamjad** [comment]
Yeah I'm pretty sure the server you're hosting it can't receive data (as Niantic blocked a lot of IP ranges). If you use Google App Engine, Azure, AWS, Heroku and tons of others then you're out of luck. You'll need to get a provider that isn't used at all (or a proxy which you can proxy through).

If you set logging as follows right after you `'require 'poke-api'`

```
Poke::API::Logging.log_level = :DEBUG
```

Then that will give you more information on your response/request object with an error code possibly in your STDOUT.
