### ISSUE TITLE
undefined method `to_h' for [["error", "invalid_grant"]]:Array

### ISSUE THREAD

**Issue by ipepe** [nabeelamjad/poke-api#43]
Poke::API::Errors::LoginFailure: Unable to login to PTC => [undefined method `to_h' for [["error", "invalid_grant"]]:Array @ /Users/user/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/auth/ptc.rb:65:in`fetch_access_token']
    from /Users/user/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:27:in `rescue in login'
    from /Users/user/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:23:in`login'

**Comment by nabeelamjad** [comment]
I will look into it, it might be easier to monkey patch the Array class to include `to_h`.

**Comment by ipepe** [comment]
Should be Hash[array]

**Comment by nabeelamjad** [comment]
I think you will get an issue with key word arguments too as they are not supported by Ruby 2.0

**Comment by nabeelamjad** [comment]
@ipepe - could you use the following snippet at the top of your code for now, I will push this fix with the next release.

``` ruby
class Array
  def to_h
    Hash[self]
  end
end
```

**Comment by ipepe** [comment]
Sure. Thanks.

**Comment by nabeelamjad** [comment]
This has been fixed now in the latest release 0.2.0
