### ISSUE TITLE
403

### ISSUE THREAD

**Issue by kddnewton** [nabeelamjad/poke-api#45]
Hi @nabeelamjad, any idea what `Poke::API::Errors::ForbiddenAccess - Your host is unable to receive a response as it is banned.` means/how it can be fixed?

**Comment by nabeelamjad** [comment]
@kddeisz it means the machine you're running from is not allowed to receive data from Niantic (they have banned the majority of providers such as AWS, Azure, Google App Engine, Linode, etc, etc).

**Comment by kddnewton** [comment]
Thanks - I'll have to find some kind of proxy I guess.
