### ISSUE TITLE
Where does this stuff come from?

### ISSUE THREAD

**Issue by nik736** [nabeelamjad/poke-api#7]
Hi there!

first of all thanks for your work.

I just have a simple question, I am currently stuck at understanding where the stuff from the fetch_endpoint method comes from:

```
get_player
get_hatched_eggs
get_inventory
check_awarded_badges
download_settings(hash: '4a2e9bc330dae60e7b74fc85b98868ab4700802e')
```

Where does it come from, what is it calling?

Thanks for any answer!

Niklas

**Comment by nabeelamjad** [comment]
Those are the RPC calls required to initiate a successful login, as to why I'm not exactly sure. I have converted these from https://github.com/tejado/pgoapi/blob/master/pgoapi/pgoapi.py#L156.

Some people intercepted the traffic using MITM and noticed these calls being made every time on login (presumably to get your login data for your profile and such ready).
